### PR TITLE
Merge upstream changes from core/master

### PR DESCRIPTION
**Pull request by jorgebay**
Migrate to dotnet 1.0.1 tools.

### CODE REVIEW

**Comment by jorgebay** [comment]
cc @landim

**Comment by landim** [comment]
For mono builds its still necessary to have the tools/nunit3-xunit.xslt

**Comment by jorgebay** [comment]
> For mono builds its still necessary to have the tools/nunit3-xunit.xslt
ok, I'll add it

**Comment by jorgebay** [comment]
It's looking good. I don't care much about the test failure transformation, let's call it for now.
If its ok for you @landim , I'll merge it once Jenkins finishes.

**Comment by landim** [comment]
I agree 👍

**Pull request merged**
