### PR TITLE
Add support for serializing TimeSpan-parameters in queries.

### PR DESCRIPTION
**Pull request by danielcweber**
Add support for serializing TimeSpan-parameters in queries. Currently, only parameters of type Duration are supported, which forces designer of POCOs to take a dependency on the driver.

### CODE REVIEW

**Comment by jorgebay** [comment]
@danielcweber we haven't forgot about your pull request, sorry for the delay in the review.

**Comment by jorgebay** [comment]
Sorry about the huge delay, I've been involved in the C# and JavaScript Gremlin variants (see [TINKERPOP-1552](https://issues.apache.org/jira/browse/TINKERPOP-1552) and [TINKERPOP-1489](https://issues.apache.org/jira/browse/TINKERPOP-1489)) amongst other things...

Maintaining multiple mappings per server type is not that easy (ie: we have to consider collections of those types) and increases the testing effort.

From our perspective, the role of the client driver is to provide accurate mapping between the server type and the client type. If we can reuse an existing type, better. In the case of `TimeSpan` vs `Duration`, there is a significant difference in:
- precision: nanos vs milliseconds.
- range: months and days vs days

We can understand that a user might not be impacted by those differences and may be inclined to use `TimeSpan`, that's why we provided conversion methods but converting is user-level decision.

In the case of a third-party library like a Mapper (as you mentioned in Slack), maybe it would make more sense to capture `TimeSpan` usages and convert to/from `Duration` without exposing it.

That said, mapping from `GraphNode` data to other types could be supported in the driver but via a pluggable interface (ie: `IGraphSONSerializer`), but should be implemented with caution as there are more than 1 version of GraphSON.

**Comment by danielcweber** [comment]
[This is how I'm currently handling the conversion](https://github.com/ExRam/ExRam.Gremlinq/blob/master/ExRam.Gremlinq.Dse/DseSessionExtensions.cs#L36) for the querying part. You mean this 'workaround' should be retained? Can this be improved?

**Comment by jorgebay** [comment]
yes, that's a good idea. You can maintain a m to n and m to n mappings there and encapsulate in some kind of `TypeMapper`.

**Pull request closed without merging**
